language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t leelawrence/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true leelawrence/docker-react npm run test
#
# Note this is the new format not
#  - docker run leelawrence/docker-react npm run test -- --coverage

#
# Automatically deploy to AWS elasticbeanstalk
#
deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-124412173695"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

